version: '3'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pokemon
      POSTGRES_USER: postgres
    networks:
      - mynetwork
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432" 


networks:
  mynetwork:
    driver: bridge
